### ISSUE TITLE
Lab 4

### ISSUE THREAD

**Issue by mohanty-sd** [alexraevn/PHYS5394-alejandro#1]
Correct the codes in lab4 to not use the Gaussian envelope to calculate instantaneous frequency.

**Comment by alexraevn** [comment]
I've corrected lab4, and thank you for your last email as well.
I understand now that the "frequency" of the gaussian curve would never be more than 1 Hz, and sine would not be chosen to have freq0<1.
 
![Gaussian Frequency Periodogram](https://user-images.githubusercontent.com/28041219/108584023-86499f00-7303-11eb-9576-83a9d6e3cbdb.png)
